import Link from "next/link";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export default function AttributionsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-b from-[#fff8f5] via-white to-[#fff0eb] font-[family-name:var(--font-geist-sans)]">
      <Header />
      <main className="flex-1 w-full max-w-2xl mx-auto px-4 sm:px-6 py-10">
        <h1 className="text-2xl font-bold text-neutral-900 mb-6">Attributions</h1>
        <div className="space-y-4 text-sm text-neutral-700 leading-relaxed">
          <p>
            Book titles and cover art shown in Bookmatch come from{" "}
            <a
              href="https://openlibrary.org"
              className="text-orange-600 underline underline-offset-2"
              target="_blank"
              rel="noopener noreferrer"
            >
              Open Library
            </a>
            , a project of the Internet Archive. Open Library data is used under
            the terms described on their site.
          </p>
          <p>
            When you use recommendations powered by Groq, suggested titles are
            generated by that service; titles and covers are still matched and
            displayed using Open Library where possible.
          </p>
        </div>
        <p className="mt-10">
          <Link
            href="/pages/home"
            className="text-sm text-orange-600 font-medium underline underline-offset-2"
          >
            ← Back to home
          </Link>
        </p>
      </main>
      <Footer />
    </div>
  );
}
